export const productTypes = [
  "Atado Escalonado",
  "Atado Tradicional",
  "Bases",
  "Boxes flowers",
  "Bouquet floral",
  "Combo floral",
  "Coronas",
  "Flores amarillas",
  "Flores y chocolates",
  "Flores fúnebres",
  "Gerberas",
  "Girasoles",
  "Globos",
  "Mega atados",
  "Orquídeas",
  "Peluches",
  "Rosas",
  "Rosas inglesas",
  "Tulipanes",
]